version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - type: bind
        source: /home/ec2-user/certs
        target: /home/revab.us
  backend:
    build: ./revab
    volumes:
      - static:/app/static
volumes:
  static:
